name: ESLint CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**/*"

jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn install --immutable
      - name: Run ESLint
        uses: sibiraj-s/action-eslint@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          eslint-args: "--config .vscode/eslint.config.ts src/"
          extensions: "js,jsx,ts,tsx"
          annotations: true
