name: Publish to npmjs
on:
  push:
    branches:
      - main
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org/'
      - name: Enable Corepack (Yarn 4.9.2)
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build and publish
        run: |
          yarn build
          yarn npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
